trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildNumber)'

stages:
- stage: Build
  displayName: Build image
  pool:
    name: Default
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: buildAndPush
        repository: modagovtw/test
        containerRegistry: modagovtw.dockerhub
        addPipelineData: false
        addBaseImageData: false
        tags: |
          latest
          $(tag)
